# Generated by Django 5.1.4 on 2024-12-29 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientId", models.CharField(max_length=20, unique=True)),
                ("age", models.PositiveIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("doctor_comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
