# Generated by Django 5.1.4 on 2024-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer_detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AlterField(
            model_name="patient",
            name="patientId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
