# Generated by Django 5.1.3 on 2024-12-31 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer_detection", "0002_remove_patient_id_alter_patient_patientid"),
    ]

    operations = [
        migrations.CreateModel(
            name="apiResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_data", models.JSONField()),
                ("full_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cancer_detection.patient",
                    ),
                ),
            ],
        ),
    ]
